// leave off @2x/@3x
const images = {
  splashBackground: require('../Images/splashBackground.png'),
  wrenchMedium: require('../Images/wrenchMedium.jpg'),
  primaryLogo: require('../Images/primaryLogo.png'),
  secondaryLogo: require('../Images/secondaryLogo.png'),
  contact: require('../Images/contact.png'),
  billing: require('../Images/billing.png'),
  share: require('../Images/share.png'),
  starInactive: require('../Images/starInactive.png'),
  starActive: require('../Images/starActive.png'),
  dashboardActive: require('../Images/dashboardActive.png'),
  dashboardInactive: require('../Images/dashboardInactive.png'),
  profileActive: require('../Images/profileActive.png'),
  profileInactive: require('../Images/profileInactive.png'),
  settings: require('../Images/settings.png'),
  back: require('../Images/chevronBack.png'),
  starRatingActive: require('../Images/starRatingActive.png'),
  starRatingInactive: require('../Images/starRatingInactive.png'),
  search: require('../Images/search.png'),
  avatar: require('../Images/avatar.jpg'),
  message: require('../Images/message.png'),
  username: require('../Images/username.png'),
  password: require('../Images/password.png'),
  exitClose: require('../Images/exitClose.png'),
  plus: require('../Images/plus.png'),
  bellActive: require('../Images/bellActive.png'),
  bellInactive: require('../Images/bellInactive.png'),
  unread: require('../Images/unread.png'),
  delete: require('../Images/delete.png'),
  showMore: require('../Images/chevronShowMore.png'),
  showLess: require('../Images/chevronShowLess.png'),
  loader: require('App/Images/Loading.gif'),
  loginScreen: require('App/Images/loginScreen.png'),
}

export default images
